[package]
name = "bevy_bones3"
version = "0.1.0"
authors = ["TheDudeFromCI <thedudefromci@gmail.com>"]
edition = "2021"
description = "A voxel world storage and mesh generation plugin for Bevy."
readme = "README.md"
homepage = "https://github.com/TheDudeFromCI/bevy_bones3"
repository = "https://github.com/TheDudeFromCI/bevy_bones3"
license = "Apache-2.0"
keywords = ["bevy", "voxel", "world", "plugin"]
categories = ["games", "game-engines"]

[dependencies]
anyhow = "1.0.66"
bevy = { version = "0.9.1", default-features = false, features = [] }
bitflags = "1.3.2"
futures-lite = "1.12.0"
itertools = "0.10.5"
ordered-float = "3.4.0"
serde = "1.0.147"

[dev-dependencies]
bevy = { version = "0.9.1", features = ["dynamic"] }
bevy_flycam = "0.9.0"
bevy_test_utils = { git = "https://github.com/TheDudeFromCI/bevy_test_utils.git", branch = "master" }
noise = "0.8.2"
pretty_assertions = "1.3.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
meshing = ["bevy/render", "bevy/bevy_asset"]
trace = ["bevy/trace"]

[[example]]
name = "terrain"
required-features = ["meshing"]
